### ISSUE TITLE
Vash

### ISSUE THREAD

**Issue by smithaitufe** [kirbysayshi/vash#119]
I came across this today while researching for how to use razor format in nodejs.

I love the work you have done.

I am interested in using this templating engine

But I want to find out if it is still very much supported.

I don't hang in the air.

I wonder why this is  not possible like other template engines out there

Your feedback is highly valued.

Thanks

**Comment by kirbysayshi** [comment]
@smithaitufe I'm not sure what you mean by "I wonder why this is not possible like other template engines out there". Are you referring to a specific feature?

Otherwise, I hope I'm interpreting you correctly when I assume your primary question is, "is vash supported". The answer is "barely". Frankly Vash no longer fulfills my own needs, so it's difficult for me to recommend it to anyone, especially in light of the arguably better and more formalized  JSX. That being said, there is no reason Vash will not function fine for the foreseeable future, as long as only ES5 and a CJS/require system is used.

**Comment by kirbysayshi** [comment]
I'm going to close this, but feel free to continue discussion if you have more questions!
