### ISSUE TITLE
ViewBag Support

### ISSUE THREAD

**Issue by zippy1981** [kirbysayshi/vash#64]
I have some views that I used with NancyFX currently that make use of the ViewBag. I'd like to be able to render these in vash. Perhaps if I could pass the ViewBag as a third parameter to the render calls.

**Comment by kirbysayshi** [comment]
I'm not familiar with NancyFX, could you describe what you're trying to do with some examples? ViewBag isn't really necessary in JS since you can just stuff whatever you want into an object. Unless I'm misunderstanding what you're looking for?

**Comment by zippy1981** [comment]
I have existing templates that require viewbag in NanvyFX. I'd like them to work from both .NET /NancyFX and vash without redoing all the Viewbag population in NancyFX.

**Comment by kirbysayshi** [comment]
In your template you could probably do something like:

```
@{ var ViewBag = model.ViewBag; }

<p>Your name is @ViewBag["name"]</p>
```

ViewBag always seemed like something C# needed because it wasn't dynamic. JS is dynamic, so it can basically just be a convention instead of a view engine feature. But it's been awhile since I used ASP MVC, I might be missing what you're asking for.

**Comment by kirbysayshi** [comment]
Hey, I'm going to close this since I haven't heard back in a while. Feel free to reopen if you want to continue the discussion :)
