### ISSUE TITLE
HTML comments can send vash into an infinite loop

### ISSUE THREAD

**Issue by Venemo** [kirbysayshi/vash#77]
Certain HTML comments can cause vash to fail.
For example:

```js
vash = require('vash');
vash.compile('<!--<a><b>c</b>-->')
```

Results in the following:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

I'm using node v0.12.2 on Fedora 22.

**Comment by Venemo** [comment]
The issue is triggered when the HTML comment contains an unclosed tag. These seem to work:

```js
vash.compile('<!--<a><b>c</b></a>-->')
vash.compile('<!-- hello -->')
```

**Comment by kirbysayshi** [comment]
Definitely a bug! Thanks for reporting. Kind of forgot about all the wrenches comments throw into the parser...

**Comment by Venemo** [comment]
I've investigated a little bit more and it seems that vash generally has a problem with unclosed HTML tags - even when it's eg. valid HTML5.

**Comment by steebchen** [comment]
@Venemo I don't see a problem there - most IDEs warn you or even auto correct the tags automatically. And just self close tags like `<meta name='..' />.

**Comment by Venemo** [comment]
@steebchen vash is a template engine, not an IDE. Why does it bother the things that are not marked with the `@` transition character?

**Comment by steebchen** [comment]
I know that it is a template engine.. I just wanted to say that most IDEs correct your tags so that vash will work.

**Comment by kirbysayshi** [comment]
@Venemo Just curious, how do you think vash should fail in this case? Presumably, in a real-world case, there would be a `</a>` waiting for vash to encounter. I suppose it should error out when it encounters that.

**Comment by kirbysayshi** [comment]
@Venemo @steebchen  whoa I'm very sorry, I missed the earlier comments between you two due to stale browser page. So I asked the previous question out of context.

@Venemo if there is a case where vash is failing, especially in regards to valid HTML5, please provide some failing code. I'm not doubting you, I'm sure there are a ton of edge cases that vash doesn't handle well, but it's much easier for me to fix specific cases. Vash tries to strike a balance between being a full HTML parser and not, and so tradeoffs are made.

As to why vash cares about anything that's not within a transition character... well that's how it used to work. But unfortunately razor syntax requires a ton of knowledge of HTML tags to know when, for example, a `}` closes a block or is just some content. Or if a `</` is part of a closing HTML tag or a regex... or to know which whitespace should be included in the output, like this: `@{ <span>hey</span> <p>hey</p> } ` (the answer is none of the whitespace, and this only comes from knowing where tags start and stop).

Another example is code like the following:

```
@{
  <p>And then you put a }</p>
}
```

In a context aware environment, like vash, the `}` within the tags will be ignored because vash knows that `}` is not a valid control character within an HTML tag. Of course things get hairy if someone decides to not close their `<p>` tags, but I think most web developers know better, even if it's allowed by the spec :)

**Comment by steebchen** [comment]
Yeah for not closing tags you should give an error message, because first, I think it's a bad style and second, some online prettifier or jsfiddle it shows an error too.
FYI, I'm using vash because I knew ASP.net MVC, but I didn't want to use vash without intellisense and syntax highlighting, so I decided to use .cshtml files and edit them. My node app 'compiles' them to .vash files so my app can use them. So circumstantial, but it's worth because I love Vash! :D

**Comment by Venemo** [comment]
@kirbysayshi If I recall correctly, I had some issues with unclosed `<li>` tags, but I'll check it tomorrow and will get back to you with specifics, if that's okay. :)

**Comment by kirbysayshi** [comment]
@Venemo Sure! No rush, just want to know what's up :)

@steebchen Thank you for the kind words! Always nice to hear people find vash useful! I'm not sure I understand about the cshtml though... are you just using the cshtml mode of visual studio to edit .vash files, or are you doing some actual post-processing to turn .cshtml files into vash syntax?

**Comment by kirbysayshi** [comment]
@steebchen @Venemo btw I investigated things around closing tags, and found that vash wasn't checking unclosed tags properly. So I've fixed that in v0.9.0, which is a breaking change. But hopefully this helps people get better errors:

```
$ node experiments/debug.js
/Users/drew/Dropbox/js/vash/lib/parser.js:131
      throw this.decorateError(
                 ^
UnclosedNodeError: Found unclosed VashMarkup at template line 2, column 1

Context:
     1 | @{
  >  2 |  <head>
     3 |  <p>HEY LISTEN</p>
     4 |  }

    at Parser.checkStack (/Users/drew/Dropbox/js/vash/lib/parser.js:129:17)
    at Object.exports.compile (/Users/drew/Dropbox/js/vash/index.js:64:5)
    at Object.<anonymous> (/Users/drew/Dropbox/js/vash/experiments/debug.js:5:17)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:117:18)
    at node.js:963:3
```

**Comment by Venemo** [comment]
@kirbysayshi You're awesome :)

**Comment by steebchen** [comment]
That's great @kirbysayshi :+1: 
I'm actually editing .cshtml files, which are then compiled to .vash files. The reason is 1) that I didn't find out how to open .vash files with the Visual Studio editor. 

    @{ dynamic model = 0, html = 0; } // this line so no error gets printed in VS
    <html>
    @{              //
        var i = 0; // These 3 lines get syntax highlighted
    }                 //
    @@model.myArray.forEach(function () { // this line would cause a syntax error, so I'm using @@ here. This line won't be syntax hightlighted. When my 'compiler' transforms the files into .vash files, he is replacing @@ with @, so it's valid vash syntax.
        <div>
            ...
        </div>
    })
    </html> 

Maybe sounds compliated, but for me it's easy and worth.
