### ISSUE TITLE
Is there a reason vash injects @model as opposed to @Model as in Razor

### ISSUE THREAD

**Issue by ichpuchtli** [kirbysayshi/vash#79]
Since ASP.NET MVC 3 ```@model``` in Razor has been a directive for binding a strongly typed model to the view accessable via the ```@Model``` variable. Wouldn't it be better for vash to inject ```@Model``` to match Razor in this way? It would make translating Razor views into vash templates dead simple.

**Comment by kirbysayshi** [comment]
There is one primary reason:

Fundamentally, Vash is for JS. and in JS variables are usually camelCase, not PascalCase. So even though Vash appeals (or appears to appeal) to C# MVC developers, I think it's very important that it be true to itself as a JS library. If I were evaluating a library and saw that its interfaces and code base were not idiomatic, I'd be highly skeptical of its quality: to me this implies an author who hasn't taken the time to learn the conventions of the environment. In fact, the original authors of RxJS went through this when they renamed all of the methods from PascalCase to camelCase to be more idiomatic to JS.

To be quite clear: I'm not referencing your wishes or you at all in the paragraph above, simply my own views on library authorship.

Because I also have a solution for you! :sunglasses: 

Vash supports what you'd like already! You just need to set `vash.config.modelName = 'Model'` before you compile your templates!

Here is an example using the vash bin:

```
echo '<p>HEY @Model.listen</p>' | bin/vash --json '{ "modelName": "Model" }' --render '{ "listen": "LISTEN" }'
```

In JS:

```
var vash = require('vash');
vash.config.modelName = 'Model';
```

I hope this helps!

**Comment by ichpuchtli** [comment]
That's a fair reason. Have you thought about injecting both, so ```@Model``` would be an alias to ```@model```? Everybody Wins haha

**Comment by kirbysayshi** [comment]
Honestly, I hadn't really considered it, I don't think anyone has brought it up before :)

Might be a bit too magical though, and might also confuse people when reading documentation.
