### ISSUE TITLE
Some email addresses are not recognized

### ISSUE THREAD

**Issue by steebchen** [kirbysayshi/vash#80]
Some emails are not recognized:
    foo@foo-bar.com // works
    foo@foo-bar.de // doesn't work

Seems that your regex `ca|co\.uk|com|edu|net|org` is a bit spare. It would be great if you either add domains like .de or edit the regex for all top level domains (I can't help you there - I hate regexes).

Here is a list of most TLDs: https://de.wikipedia.org/wiki/Top-Level-Domain

**Comment by kirbysayshi** [comment]
Thanks for the bug report. I've been hesitant to include every tld since email address parsing is already so error prone. But I'll look again, maybe it's not too bad now.

In the meantime, a workaround for you is to either use an explicit expression: `@("foo@foo-bar.de")` or manually escape the `@`: `foo@@foo-bar.de`

**Comment by kirbysayshi** [comment]
@steebchen Two letters should be included as email addresses now! Hope this helps. v0.9.2

**Comment by steebchen** [comment]
Great!
