### ISSUE TITLE
Support for multiple @{name} helpers

### ISSUE THREAD

**Issue by ETNOL** [kirbysayshi/vash#97]
I'm trying to use vash to render cshtml files. I'm having decent luck after extending the helpers as needed but I'm stuck on rendering the @helper () { } methods in my razor files.

Is there a not-so-painful way to create another @{namespace} like @html that acts as like razor's @helper? 

I know this isn't vash's intended use but, since I'm _pretty_ close to pulling it off, I figured I'd ask if this was possible.

**Comment by kirbysayshi** [comment]
It's currently not possible to have multiple internal namespaces for a template, since that is defined all the way from the config, through the compiler, and even in the runtime / linker. But you could hack this with some sort of globals, I suppose. But that sounds pretty hacky.

You might be better off preprocessing your cshtml files with a regex that replaces the `@helper` keyword with an assignment to a global namespace?
